-- 软考表关闭 RLS（后端使用自定义 JWT，非 Supabase Auth；anon/service 需可读写）
ALTER TABLE IF EXISTS ruankao_questions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ruankao_attempts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ruankao_wrong_book DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ruankao_checkins DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ruankao_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ruankao_knowledge DISABLE ROW LEVEL SECURITY;
